{% set version = "11.4.0.6" %}
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "linux-x86_64" %}  # [linux64]
{% set extension = "tar.xz" %}  # [unix]

{% set cuda_compiler_version = cuda_compiler_version|default("None") %}

{% set sha256 = "6a0597e10e698ab46ea9a607efe06f681ba6e2bf0d8eddd8a72a09c18a8f7253" %}  # [linux64]
{% set sha256 = "c0f944fd6ef2e13ef5adfd48ef2e02660f5f573a69c515580096a9eaae13be16" %}  # [aarch64]

package:
  name: libcufftmp-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cufftmp/redist/libcufftmp/{{ platform }}/libcufftmp-{{ platform }}-{{ version }}_cuda12-archive.{{ extension }}  # [(cuda_compiler_version or "").startswith("12")]
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [(cuda_compiler_version in (None, "None", "11.8")) or (not (linux64 or aarch64))]

requirements:
  build:
    - cf-nvidia-tools 1  # [linux]

outputs:

  - name: libcufftmp
    build:
      ignore_run_exports_from:
        - {{ compiler('cuda') }}
    files:
      - lib/libcufftMp.so.*
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - {{ compiler('cuda') }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
        - libnvshmem-dev 3
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}  # [cuda_compiler_version != "None"]
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -f $PREFIX/lib/libcufftMp.so.11
        - test -f $PREFIX/lib/libcufftMp.so.11.4.0

  - name: libcufftmp-dev
    build:
      run_exports:
        - {{ pin_subpackage("libcufftmp", max_pin=None) }}
    files:
      - lib/libcufftMp.so
      - include/cufftMp.h
      - include/cufft.h
      - include/cudalibxt.h
      - include/cufftXt.h
    requirements:
      host:
        - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
        - {{ pin_subpackage("libcufftmp", exact=True) }}
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}  # [cuda_compiler_version != "None"]
        - {{ pin_subpackage("libcufftmp", exact=True) }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -f $PREFIX/lib/libcufftMp.so
        - test -f $PREFIX/include/cudalibxt.h
        - test -f $PREFIX/include/cufft.h
        - test -f $PREFIX/include/cufftMp.h
        - test -f $PREFIX/include/cufftXt.h

about:
  home: https://docs.nvidia.com/hpc-sdk/cufftmp
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file: LICENSE
  license_url: https://docs.nvidia.com/cuda/cublasdx/license.html
  summary: The NVIDIA cuFFTMp (cuFFT Multi-process) library
  description: >-
    The multi-node FFT functionality, available through the cuFFTMp API, enables
    scientists and engineers to solve distributed 2D and 3D FFTs in exascale
    problems. The library handles all the communications between machines,
    allowing users to focus on other aspects of their problems.
  doc_url: https://docs.nvidia.com/hpc-sdk/cufftmp

extra:
  recipe-maintainers:
    - conda-forge/cuda
  feedstock-name: libcufftmp
