{% set version = "12.1.3.2" %}
{% set abiversion = version.split('.')[0] %}
{% set libversion = version.split('.')[:3] | join('.') %}
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "linux-x86_64" %}  # [linux64]
{% set extension = "tar.xz" %}  # [unix]

{% set cuda_compiler_version = cuda_compiler_version | default("None") %}
{% set cuda_major_version = cuda_compiler_version.split('.')[0] %}

{% set sha256 = "3f4e447d0fb3571ddd751cd7215f182a1c14dbc4ff23cdfc988ef491a6cc984a" %}  # [linux64]
{% set sha256 = "17482614488d9ed190d576ba041762df8252b9a67768cbc118042c6603a78c19" %}  # [aarch64]

package:
  name: libcufftmp-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cufftmp/redist/libcufftmp/{{ platform }}/libcufftmp-{{ platform }}-{{ version }}_cuda13-archive.{{ extension }}  # [(cuda_compiler_version or "").startswith("13")]
  sha256: {{ sha256 }}

build:
  script_env:
    - CUDA_MAJOR_VERSION={{ cuda_major_version }}
  number: 0
  skip: true  # [(cuda_compiler_version or "").startswith("12") or cuda_compiler_version == "None" or not (linux64 or aarch64)]

requirements:
  build:
    - cf-nvidia-tools 1  # [linux]

outputs:

  - name: libcufftmp
    build:
      ignore_run_exports_from:
        - {{ compiler('cuda') }}
    files:
      - lib/libcufftMp.so.*
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - {{ compiler('cuda') }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
        - libnvshmem-dev 3
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}  # [cuda_compiler_version != "None"]
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -f $PREFIX/lib/libcufftMp.so.{{ abiversion }}
        - test -f $PREFIX/lib/libcufftMp.so.{{ libversion }}

  - name: libcufftmp-dev
    build:
      run_exports:
        - {{ pin_subpackage("libcufftmp", max_pin=None) }}
    files:
      - lib/libcufftMp.so
      - include/cufftMp.h
      - include/cufft.h
      - include/cudalibxt.h
      - include/cufftXt.h
    requirements:
      host:
        - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
        - {{ pin_subpackage("libcufftmp", exact=True) }}
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}  # [cuda_compiler_version != "None"]
        - {{ pin_subpackage("libcufftmp", exact=True) }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -f $PREFIX/lib/libcufftMp.so
        - test -f $PREFIX/include/cudalibxt.h
        - test -f $PREFIX/include/cufft.h
        - test -f $PREFIX/include/cufftMp.h
        - test -f $PREFIX/include/cufftXt.h

about:
  home: https://docs.nvidia.com/cuda/cufftmp/
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file: LICENSE
  license_url: https://docs.nvidia.com/cuda/cufftmp/license.html
  summary: The NVIDIA cuFFTMp (cuFFT Multi-process) library
  description: >-
    The multi-node FFT functionality, available through the cuFFTMp API, enables
    scientists and engineers to solve distributed 2D and 3D FFTs in exascale
    problems. The library handles all the communications between machines,
    allowing users to focus on other aspects of their problems.
  doc_url: https://docs.nvidia.com/cuda/cufftmp/

extra:
  recipe-maintainers:
    - conda-forge/cuda
  feedstock-name: libcufftmp
